vich_uploader:
    db_driver: orm
    
    mappings:
        cv:
            uri_prefix: /uploads/files
            upload_destination: '%kernel.project_dir%/public/uploads/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false

